# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

ansible_vars = YAML.load_file('provisioning/preferences-server-vars.yml')

app_name = "gpii-components"

app_start_script = ansible_vars["nodejs_app_start_script"]

app_directory = "/home/vagrant/sync"

# Check for the existence of 'VM_HOST_TCP_PORT' or 'VM_GUEST_TCP_PORT'
# environment variables. Otherwise if 'nodejs_app_tcp_port' is defined
# in vars.yml then use that port. Failing that use defaults provided
# in this file.
#host_tcp_port = ENV["VM_HOST_TCP_PORT"] || ansible_vars["nodejs_app_tcp_port"] || 8081
#guest_tcp_port = ENV["VM_GUEST_TCP_PORT"] || ansible_vars["nodejs_app_tcp_port"] || 8081

# By default this VM will use 1 processor core and 1GB of RAM. The 'VM_CPUS' and
# "VM_RAM" environment variables can be used to change that behaviour.
cpus = ENV["VM_CPUS"] || 1
ram = ENV["VM_RAM"] || 1048

Vagrant.configure(2) do |config|

  config.vm.box = "inclusivedesign/centos7"

  # The main Universal root directory will be synced to /home/vagrant/sync in the VM.
  config.vm.synced_folder "..", "#{app_directory}"

  # List additional directories to sync to the VM in your "Vagrantfile.local" file
  # using the following format:
  # config.vm.synced_folder "../path/on/your/host/os/your-project", "/home/vagrant/sync/your-project"

  # Port forwarding takes place here. The 'guest' port is used inside the VM
  # whereas the 'host' port is used by your host operating system.
  #config.vm.network "forwarded_port", guest: guest_tcp_port, host: host_tcp_port, protocol: "tcp",
  #  auto_correct: true

  # Port forwarding for CouchDB
  config.vm.network "forwarded_port", guest: 5984, host: 5984, protocol: "tcp",
    auto_correct: true

  # Port forwarding for Preferences Server
  config.vm.network "forwarded_port", guest: 8081, host: 8081, protocol: "tcp",
    auto_correct: true

  # Port forwarding for Flow Manager
  config.vm.network "forwarded_port", guest: 8082, host: 8082, protocol: "tcp",
    auto_correct: true

  # Port 19531 is needed so logs can be viewed using systemd-journal-gateway
  config.vm.network "forwarded_port", guest: 19531, host: 19531, protocol: "tcp",
    auto_correct: true

  config.vm.hostname = app_name

  config.vm.provider :virtualbox do |vm|
    vm.customize ["modifyvm", :id, "--memory", ram]
    vm.customize ["modifyvm", :id, "--cpus", cpus]
  end

  config.vm.provision "shell", path: "./provisioning/deploy.sh"

  # 'Vagrantfile.local' should be excluded from version control.
  if File.exist? "Vagrantfile.local"
    instance_eval File.read("Vagrantfile.local"), "Vagrantfile.local"
  end

  config.vm.provision "shell", inline: "sudo systemctl restart preferences-server.service",
    run: "always"

  config.vm.provision "shell", inline: "sudo systemctl restart flow-manager.service",
    run: "always"

  config.vm.provision "shell", inline: "sudo systemctl restart systemd-journal-gatewayd.service",
    run: "always"

end
